package com.nulldata.app.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext

data class AppStrings(
    // General
    val appName: String,
    val continueBtn: String,
    val cancel: String,
    val copy: String,
    val paste: String,
    val edit: String,
    val delete: String,
    val save: String,
    val back: String,
    val confirm: String,
    val unlock: String,
    val encrypt: String,
    val decrypt: String,

    // Language Screen
    val chooseLanguage: String,
    val langSubtitle: String,

    // Login
    val loginTitle: String,
    val masterPassword: String,
    val loginButton: String,
    val forgotPassword: String,
    val resetWarning: String,

    // Setup
    val setupTitle: String,
    val setupSubtitle: String,
    val setupCreatePassword: String,
    val setupConfirmPassword: String,
    val setupCreateBtn: String,
    val setupPasswordMismatch: String,
    val setupPasswordShort: String,
    val setupSecureVault: String,
    val setupDecoyVault: String,
    val setupEnableDecoy: String,
    val setupDecoyPassword: String,
    val setupDecoyHint: String,

    // Notes List
    val allNotes: String,
    val favorites: String,
    val decoyNotes: String,
    val noNotes: String,
    val createNote: String,
    val searchNotes: String,
    val encryptedNote: String,
    val noteModified: String,
    val noFavorites: String,

    // Note Editor
    val editNote: String,
    val newNote: String,
    val noteTitle: String,
    val noteContent: String,
    val noteKey: String,
    val createKey: String,
    val enterKeyToDecrypt: String,
    val encryptedMessage: String,
    val disguisedUrl: String,
    val disguiseAs: String,
    val disguiseAsLink: String,
    val generateKey: String,
    val keyRequired: String,
    val keyTooShort: String,
    val wrongKey: String,
    val minChars: String,
    val keysMatch: String,
    val discardNoteTitle: String,
    val discardNoteMsg: String,
    val stay: String,
    val discard: String,
    val enterNoteKey: String,
    val reEnterKeyToUnlock: String,
    val encryptNote: String,

    // Encrypt/Decrypt
    val encryptDecryptTitle: String,
    val encryptTab: String,
    val decryptTab: String,
    val decoyTab: String,
    val plaintext: String,
    val encryptedBlob: String,
    val encryptionKey: String,
    val encrypting: String,
    val decrypting: String,
    val encryptedOutput: String,
    val decrypted: String,
    val encryptFailed: String,
    val decryptFailed: String,
    val invalidBlob: String,
    val pasteUrlFirst: String,
    val invalidUrl: String,
    val extractedBlob: String,
    val decode: String,
    val switchToDecrypt: String,
    val disabledUrlPasteHint: String,
    val decoyHint: String,

    // Trash
    val trash: String,
    val noTrash: String,
    val restore: String,
    val deleteForever: String,

    // Settings
    val settings: String,
    val darkTheme: String,
    val biometricLock: String,
    val changePassword: String,
    val currentPassword: String,
    val newPassword: String,
    val confirmNewPassword: String,
    val passwordChanged: String,
    val passwordChangedSubtitle: String,
    val ok: String,
    val autoLockOff: String,
    val autoLock1min: String,
    val autoLock5min: String,
    val autoLock15min: String,
    val autoLock30min: String,
    val autoLock1hr: String,
    val settingsDecoySetup: String,
    val settingsDecoySubtitle: String,
    val autoLockTimeout: String,
    val securityLevel: String,

    // Export/Import
    val exportImport: String,
    val exportTitle: String,
    val importTitle: String,
    val exportPassword: String,
    val exportFile: String,
    val importFile: String,
    val exportSuccess: String,
    val importSuccess: String,

    // About
    val about: String,
    val aboutVersion: String,
    val aboutDescription: String,
    val aboutLicense: String,
    val aboutTechStack: String,
    val aboutThreatModelTitle: String,
    val aboutThreatModel: String,
    val aboutCommunityTitle: String,
    val aboutDiscordApp: String,
    val aboutDiscordDev: String,
    val aboutInsta: String,
    val aboutFacebook: String,
    val aboutSignalGroup: String,

    // Sidebar
    val sidebarSecureVault: String,
    val sidebarDecoyVault: String,
    val sidebarAllNotes: String,
    val sidebarFavorites: String,
    val sidebarEncryptDecrypt: String,
    val sidebarTrash: String,
    val sidebarSettings: String,
    val sidebarExportImport: String,
    val sidebarAbout: String,
    val sidebarLockVault: String,

    // Exit dialog
    val exitTitle: String,
    val exitMessage: String,
    val exitConfirm: String,
    val exitCancel: String,

    // Other
    // Settings subtitles
    val darkThemeSubtitle: String,
    val rootDetectionTitle: String,
    val rootDetectionSubtitle: String,
    val securityDetails: String,
    val language: String,
    val selectLanguage: String,

    // Info / Instructions
    val sidebarInstructions: String,
    val instructionsTitle: String,
    val instructionsIntro: String,
    val instructionsPasswordTitle: String,
    val instructionsPasswordDetails: String,
    val instructionsPaperTitle: String,
    val instructionsPaperDetails: String,
    val instructionsNoDigitalTitle: String,
    val instructionsNoDigitalDetails: String,
    val instructionsNoReadAloudTitle: String,
    val instructionsNoReadAloudDetails: String,
    val instructionsHowToEncryptTitle: String,
    val instructionsHowToEncryptDetails: String,
    val instructionsHowToDecryptTitle: String,
    val instructionsHowToDecryptDetails: String,
    val instructionsMultiUserTitle: String,
    val instructionsMultiUserDetails: String,
    val instructionsMultiUserFriends: String,
    val instructionsMultiUserFriendsDetails: String,
    val instructionsCheckWebsite: String,
    val instructionsMistakesTitle: String,
    val instructionsMistake1: String,
    val instructionsMistake2: String,
    val instructionsMistake3: String,
    val instructionsMistake4: String,
    val instructionsWarningTitle: String,
    val instructionsWarning1: String,
    val instructionsWarning2: String,
    val instructionsWarning3: String,

    // Instructions first-time prompt
    val instructionsPromptTitle: String,
    val instructionsPromptMessage: String,
    val instructionsPromptView: String,
    val instructionsPromptSkip: String,

    // Common actions
    val copied: String,
    val decoded: String,
    val platform: String,
    val noDecoyNotes: String,
)

val LocalStrings = compositionLocalOf { englishStrings }
val LocalLanguageCode = compositionLocalOf { "en" }

@Composable
fun rememberStrings(): AppStrings {
    val lang = LocalLanguageCode.current
    return stringsFor(lang)
}

fun stringsFor(languageCode: String): AppStrings = when (languageCode) {
    "de" -> germanStrings
    "ckb" -> soraniStrings
    "kmr" -> kurmanjiStrings
    "tr" -> turkishStrings
    else -> englishStrings
}

val englishStrings = AppStrings(
    appName = "Taybeti",
    continueBtn = "Continue",
    cancel = "Cancel",
    copy = "Copy",
    paste = "Paste",
    edit = "Edit",
    delete = "Delete",
    save = "Save",
    back = "Back",
    confirm = "Confirm",
    ok = "OK",
    unlock = "Unlock",
    encrypt = "Encrypt",
    decrypt = "Decrypt",

    chooseLanguage = "Choose your language",
    langSubtitle = "Zimanê xwe hilbijêre",

    loginTitle = "Unlock Vault",
    masterPassword = "Master Password",
    loginButton = "Unlock",
    forgotPassword = "Forgot Password?",
    resetWarning = "You will lose all data. Are you sure?",

    setupTitle = "Welcome to Taybeti",
    setupSubtitle = "Set up your secure vault",
    setupCreatePassword = "Create Master Password",
    setupConfirmPassword = "Confirm Master Password",
    setupCreateBtn = "Create Vault",
    setupPasswordMismatch = "Passwords do not match",
    setupPasswordShort = "Minimum 8 characters",
    setupSecureVault = "Secure Vault",
    setupDecoyVault = "Decoy Vault",
    setupEnableDecoy = "Enable decoy vault",
    setupDecoyPassword = "Decoy Password",
    setupDecoyHint = "Enter a password for the decoy vault (optional)",

    allNotes = "All Notes",
    favorites = "Favorites",
    decoyNotes = "Decoy Notes",
    noNotes = "No notes yet",
    createNote = "Create Note",
    searchNotes = "Search notes...",
    encryptedNote = "Encrypted",
    noteModified = "Modified",
    noFavorites = "No favorites yet",

    editNote = "Edit Note",
    newNote = "New Note",
    noteTitle = "Note title",
    noteContent = "Note content",
    noteKey = "Note key",
    createKey = "Create Key",
    enterKeyToDecrypt = "Enter the key to decrypt this note",
    encryptedMessage = "Encrypted Message:",
    disguisedUrl = "Disguised URL",
    disguiseAs = "Disguise as",
    disguiseAsLink = "Disguise as shareable link",
    generateKey = "Generate Secure Key",
    keyRequired = "Key is required",
    keyTooShort = "Key too short (min 8 characters)",
    wrongKey = "Wrong key",
    minChars = "Minimum 8 characters",
    keysMatch = "Keys do not match",
    discardNoteTitle = "Discard note?",
    discardNoteMsg = "You have unsaved content. Encrypt first to save it, or discard your changes.",
    stay = "Stay",
    discard = "Discard",
    enterNoteKey = "Enter Note Key",
    reEnterKeyToUnlock = "Re-enter the key to unlock and edit this note.",
    encryptNote = "Encrypt Note",

    encryptDecryptTitle = "Encrypt / Decrypt",
    encryptTab = "Encrypt",
    decryptTab = "Decrypt",
    decoyTab = "Decoy",
    plaintext = "Plaintext",
    encryptedBlob = "Encrypted blob",
    encryptionKey = "Encryption key",
    encrypting = "Encrypting...",
    decrypting = "Decrypting...",
    encryptedOutput = "Encrypted Output:",
    decrypted = "Decrypted:",
    encryptFailed = "Encryption failed",
    decryptFailed = "Decryption failed (wrong key or corrupted data)",
    invalidBlob = "Invalid blob format",
    pasteUrlFirst = "Paste a URL first",
    invalidUrl = "Invalid URL for selected platform",
    extractedBlob = "Extracted encrypted blob:",
    decode = "Decode",
    switchToDecrypt = "Switch to the Decrypt tab, paste this blob, and enter your key to decrypt.",
    disabledUrlPasteHint = "Paste a disguised URL to extract the encrypted message.",
    decoyHint = "Paste a disguised URL to extract the encrypted message.",

    trash = "Trash",
    noTrash = "Trash is empty",
    restore = "Restore",
    deleteForever = "Delete Forever",

    settings = "Settings",
    darkTheme = "Dark Theme",
    biometricLock = "Biometric Lock",
    changePassword = "Change Password",
    currentPassword = "Current Password",
    newPassword = "New Master Password",
    confirmNewPassword = "Confirm New Password",
    passwordChanged = "Password Changed",
    passwordChangedSubtitle = "Restart the app to use your new password. Your notes are safe.",
    autoLockOff = "Off",
    autoLock1min = "1 minute",
    autoLock5min = "5 minutes",
    autoLock15min = "15 minutes",
    autoLock30min = "30 minutes",
    autoLock1hr = "1 hour",
    settingsDecoySetup = "Setup Decoy Password",
    settingsDecoySubtitle = "Add a decoy password to hide your real data",
    autoLockTimeout = "Auto-Lock Timeout",
    securityLevel = "Security Level",

    exportImport = "Export / Import",
    exportTitle = "Export",
    importTitle = "Import",
    exportPassword = "Export Password",
    exportFile = "Export File",
    importFile = "Import File",
    exportSuccess = "Exported successfully",
    importSuccess = "Imported successfully",

    about = "About",
    aboutVersion = "Version",
    aboutDescription = "A secure note app with military-grade encryption.",
    aboutLicense = "MIT License",
    aboutTechStack = "Tech Stack:\n• Kotlin + Jetpack Compose\n• AES-256-GCM encryption\n• Argon2id key derivation (64MB)\n• Room database (SQLCipher)\n• No internet permission\n• No Google Play Services",
    aboutThreatModelTitle = "Threat Model",
    aboutThreatModel = "Designed to protect against:\n• Physical device seizure (encrypted-at-rest)\n• Malicious apps (no IPC, FLAG_SECURE)\n• Keyboard logging (custom keyboard)\n• Screenshot capture (FLAG_SECURE)\n• Android backup extraction (backup disabled)\n• Cloud sync leaks (no internet)\n• Google/OS key extraction (no Keystore)\n\nLimitations:\n• Does not protect against compromised OS kernel\n• Does not protect against hardware keyloggers\n• RAM contains plaintext while note is open",
    aboutCommunityTitle = "Join my community",
    aboutDiscordApp = "Taybeti Discord",
    aboutDiscordDev = "My Discord",
    aboutInsta = "My Instagram",
    aboutFacebook = "My Facebook",
    aboutSignalGroup = "Signal Group",

    sidebarSecureVault = "Secure Vault",
    sidebarDecoyVault = "Decoy Vault",
    sidebarAllNotes = "All Notes",
    sidebarFavorites = "Favorites",
    sidebarEncryptDecrypt = "Encrypt/Decrypt",
    sidebarTrash = "Trash",
    sidebarSettings = "Settings",
    sidebarExportImport = "Export/Import",
    sidebarAbout = "About",
    sidebarLockVault = "Lock Vault",

    exitTitle = "Exit Taybeti?",
    exitMessage = "Are you sure you want to exit?",
    exitConfirm = "Exit",
    exitCancel = "Cancel",

    copied = "Copied",
    decoded = "Decoded",
    platform = "Platform",
    noDecoyNotes = "No decoy notes",

    darkThemeSubtitle = "Switch between dark and light appearance",
    rootDetectionTitle = "Root Detection Warning",
    rootDetectionSubtitle = "Warn if device is rooted (less secure)",
    securityDetails = "After 5 failed login attempts, a 30-second lockout is enforced.\nAll encryption keys are derived using Argon2id with 64MB memory.\nPasswords are stored as char[] and zeroed after use.",
    language = "Language",
    selectLanguage = "Select language",

    sidebarInstructions = "Instructions",
    instructionsTitle = "Security Instructions",
    instructionsIntro = "Read carefully. Your security depends on following these steps.",
    instructionsPasswordTitle = "1. Choose your master password in person",
    instructionsPasswordDetails = "When creating your master password, make sure nobody is watching. Do not look at your screen while typing if cameras are nearby. Use a combination of uppercase, lowercase, numbers and symbols. Minimum 8 characters — longer is better.",
    instructionsPaperTitle = "2. Write it on paper",
    instructionsPaperDetails = "Never store your password digitally (no screenshots, no notes app, no cloud). Write it on physical paper and keep it in a safe place. If someone finds your paper, they still need your phone. If someone gets your phone, they still need your paper.",
    instructionsNoDigitalTitle = "3. Never save passwords digitally",
    instructionsNoDigitalDetails = "Do not save passwords in any digital form — no text files, no password managers, no email drafts, no cloud notes. Digital copies can be copied, hacked, or subpoenaed. Paper only.",
    instructionsNoReadAloudTitle = "4. Never read your password aloud",
    instructionsNoReadAloudDetails = "Modern spyware can activate your phone's microphone without visible indicators. Never speak your password. Never type it while someone can hear the key taps. Assume your device is always listening.",
    instructionsHowToEncryptTitle = "How to encrypt a message",
    instructionsHowToEncryptDetails = "Open Encrypt tab → type your message → enter a strong passphrase (or tap Generate Key) → tap Encrypt. Copy the output safely. Optionally disguise the encrypted text as a URL using the platform dropdown.",
    instructionsHowToDecryptTitle = "How to decrypt a message",
    instructionsHowToDecryptDetails = "If you received a disguised URL: paste it in the Decoy tab, select the platform, tap Decode. Then switch to the Decrypt tab, paste the extracted blob, enter the key, and tap Decrypt. If you received the raw encrypted blob, paste it directly in the Decrypt tab.",
    instructionsMultiUserTitle = "Multi-User Encryption",
    instructionsMultiUserDetails = "When two or more people want to exchange encrypted messages: meet in person to create the passphrase together. Each person writes it on paper and keeps it in an extremely safe place. The passphrase must NEVER be sent digitally — not via SMS, messaging app, email, or cloud. Only the encrypted output should ever leave your device.",
    instructionsMultiUserFriends = "Share Encryption with Friends & Family",
    instructionsMultiUserFriendsDetails = "Meet in person to agree on a shared passphrase. Each person writes it down on paper — never type it into a messaging app. Use the Encrypt tool to encrypt your message, then share only the encrypted output (text or link) via any chat app. The recipient uses the Decrypt tool with the same passphrase to read it.",
    instructionsCheckWebsite = "🔁 Check for updates: Visit our website regularly for newer versions and security improvements:\nhttps://cyberboy161.github.io/Taybeti/",
    instructionsMistakesTitle = "Common mistakes to avoid",
    instructionsMistake1 = "❌ Using the same password for multiple notes or accounts",
    instructionsMistake2 = "❌ Storing keys in cloud notes, email, or messaging apps",
    instructionsMistake3 = "❌ Typing passwords in public places with cameras or shoulder-surfers",
    instructionsMistake4 = "❌ Using short, dictionary-based, or predictable passwords",
    instructionsWarningTitle = "⚠️ Important warnings",
    instructionsWarning1 = "NEVER share your master password with anyone — not even support or law enforcement",
    instructionsWarning2 = "If you forget your password, your data CANNOT be recovered — there is no backdoor",
    instructionsWarning3 = "After 5 wrong attempts, a 30-second lockout activates — this prevents brute-force attacks",

    instructionsPromptTitle = "Read Security Instructions",
    instructionsPromptMessage = "We strongly recommend reading the security instructions before using the app. They explain how to keep your data safe from spyware, keyloggers, and surveillance.",
    instructionsPromptView = "View Instructions",
    instructionsPromptSkip = "Skip",
)

val germanStrings = englishStrings.copy(
    continueBtn = "Weiter",
    cancel = "Abbrechen",
    copy = "Kopieren",
    paste = "Einfügen",
    edit = "Bearbeiten",
    delete = "Löschen",
    save = "Speichern",
    back = "Zurück",
    confirm = "Bestätigen",
    ok = "OK",
    unlock = "Entsperren",
    encrypt = "Verschlüsseln",
    decrypt = "Entschlüsseln",
    chooseLanguage = "Wähle deine Sprache",
    langSubtitle = "Zimanê xwe hilbijêre",
    loginTitle = "Tresor entsperren",
    masterPassword = "Master-Passwort",
    loginButton = "Entsperren",
    forgotPassword = "Passwort vergessen?",
    resetWarning = "Alle Daten gehen verloren. Bist du sicher?",
    setupTitle = "Willkommen bei Taybeti",
    setupSubtitle = "Richte deinen sicheren Tresor ein",
    setupCreatePassword = "Master-Passwort erstellen",
    setupConfirmPassword = "Master-Passwort bestätigen",
    setupCreateBtn = "Tresor erstellen",
    setupPasswordMismatch = "Passwörter stimmen nicht überein",
    setupPasswordShort = "Mindestens 8 Zeichen",
    setupSecureVault = "Sicherer Tresor",
    setupDecoyVault = "Tarn-Tresor",
    setupEnableDecoy = "Tarn-Tresor aktivieren",
    setupDecoyPassword = "Tarn-Passwort",
    setupDecoyHint = "Gib ein Passwort für den Tarn-Tresor ein (optional)",
    allNotes = "Alle Notizen",
    favorites = "Favoriten",
    decoyNotes = "Tarn-Notizen",
    noNotes = "Noch keine Notizen",
    createNote = "Notiz erstellen",
    searchNotes = "Notizen durchsuchen...",
    encryptedNote = "Verschlüsselt",
    noteModified = "Geändert",
    noFavorites = "Noch keine Favoriten",
    editNote = "Notiz bearbeiten",
    newNote = "Neue Notiz",
    noteTitle = "Titel",
    noteContent = "Inhalt",
    noteKey = "Notiz-Schlüssel",
    createKey = "Schlüssel erstellen",
    enterKeyToDecrypt = "Gib den Schlüssel ein um diese Notiz zu entschlüsseln",
    encryptedMessage = "Verschlüsselte Nachricht:",
    disguisedUrl = "Getarnte URL",
    disguiseAs = "Tarnen als",
    disguiseAsLink = "Als teilbaren Link tarnen",
    generateKey = "Sicheren Schlüssel generieren",
    keyRequired = "Schlüssel erforderlich",
    keyTooShort = "Schlüssel zu kurz (min. 8 Zeichen)",
    wrongKey = "Falscher Schlüssel",
    minChars = "Mindestens 8 Zeichen",
    keysMatch = "Schlüssel stimmen nicht überein",
    discardNoteTitle = "Notiz verwerfen?",
    discardNoteMsg = "Du hast ungespeicherte Inhalte. Verschlüssle zuerst zum Speichern, oder verwerfe die Änderungen.",
    stay = "Bleiben",
    discard = "Verwerfen",
    enterNoteKey = "Notiz-Schlüssel eingeben",
    reEnterKeyToUnlock = "Gib den Schlüssel erneut ein um die Notiz zu entsperren.",
    encryptNote = "Notiz verschlüsseln",
    encryptDecryptTitle = "Verschlüsseln / Entschlüsseln",
    encryptTab = "Verschlüsseln",
    decryptTab = "Entschlüsseln",
    decoyTab = "Tarnung",
    plaintext = "Klartext",
    encryptedBlob = "Verschlüsselter Text",
    encryptionKey = "Verschlüsselungsschlüssel",
    encrypting = "Verschlüssle...",
    decrypting = "Entschlüssle...",
    encryptedOutput = "Verschlüsselte Ausgabe:",
    decrypted = "Entschlüsselt:",
    encryptFailed = "Verschlüsselung fehlgeschlagen",
    decryptFailed = "Entschlüsselung fehlgeschlagen (falscher Schlüssel oder beschädigte Daten)",
    invalidBlob = "Ungültiges Format",
    pasteUrlFirst = "Füge zuerst eine URL ein",
    invalidUrl = "Ungültige URL für die gewählte Plattform",
    extractedBlob = "Extrahierter verschlüsselter Text:",
    decode = "Dekodieren",
    switchToDecrypt = "Wechsle zum Entschlüsseln-Tab, füge den Text ein und gib deinen Schlüssel ein.",
    disabledUrlPasteHint = "Füge eine getarnte URL ein um die verschlüsselte Nachricht zu extrahieren.",
    decoyHint = "Füge eine getarnte URL ein um die verschlüsselte Nachricht zu extrahieren.",
    trash = "Papierkorb",
    noTrash = "Papierkorb ist leer",
    restore = "Wiederherstellen",
    deleteForever = "Endgültig löschen",
    settings = "Einstellungen",
    darkTheme = "Dunkles Design",
    biometricLock = "Biometrische Sperre",
    changePassword = "Passwort ändern",
    currentPassword = "Aktuelles Passwort",
    newPassword = "Neues Master-Passwort",
    confirmNewPassword = "Neues Passwort bestätigen",
    passwordChanged = "Passwort geändert",
    passwordChangedSubtitle = "Starten Sie die App neu, um Ihr neues Passwort zu verwenden. Ihre Notizen sind sicher.",
    autoLockOff = "Aus",
    autoLock1min = "1 Minute",
    autoLock5min = "5 Minuten",
    autoLock15min = "15 Minuten",
    autoLock30min = "30 Minuten",
    autoLock1hr = "1 Stunde",
    settingsDecoySetup = "Tarn-Passwort einrichten",
    settingsDecoySubtitle = "Füge ein Tarn-Passwort hinzu um echte Daten zu verstecken",
    autoLockTimeout = "Auto-Sperre Zeit",
    securityLevel = "Sicherheitsstufe",
    exportImport = "Export / Import",
    exportTitle = "Export",
    importTitle = "Import",
    exportPassword = "Export-Passwort",
    exportFile = "Export-Datei",
    importFile = "Import-Datei",
    exportSuccess = "Erfolgreich exportiert",
    importSuccess = "Erfolgreich importiert",
    about = "Über",
    aboutVersion = "Version",
    aboutDescription = "Eine sichere Notiz-App mit Verschlüsselung auf Militärniveau.",
    aboutLicense = "MIT-Lizenz",
    aboutTechStack = "Tech-Stack:\n• Kotlin + Jetpack Compose\n• AES-256-GCM Verschlüsselung\n• Argon2id Schlüsselableitung (64MB)\n• Room Datenbank (SQLCipher)\n• Keine Internetberechtigung\n• Keine Google Play Services",
    aboutThreatModelTitle = "Bedrohungsmodell",
    aboutThreatModel = "Schützt gegen:\n• Physische Beschlagnahme (verschlüsselt)\n• Bösartige Apps (kein IPC, FLAG_SECURE)\n• Tastatur-Logging (eigene Tastatur)\n• Screenshot-Aufnahme (FLAG_SECURE)\n• Android-Backup-Extraktion (deaktiviert)\n• Cloud-Sync-Lecks (kein Internet)\n• Google/OS Schlüsselextraktion (kein Keystore)\n\nEinschränkungen:\n• Schützt nicht gegen kompromittierten OS-Kernel\n• Schützt nicht gegen Hardware-Keylogger\n• RAM enthält Klartext während Notiz geöffnet ist",
    aboutCommunityTitle = "Tritt meiner Community bei",
    sidebarSecureVault = "Sicherer Tresor",
    sidebarDecoyVault = "Tarn-Tresor",
    sidebarAllNotes = "Alle Notizen",
    sidebarFavorites = "Favoriten",
    sidebarEncryptDecrypt = "Ver-/Entschlüsseln",
    sidebarTrash = "Papierkorb",
    sidebarSettings = "Einstellungen",
    sidebarExportImport = "Export/Import",
    sidebarAbout = "Über",
    sidebarLockVault = "Tresor sperren",
    exitTitle = "Taybeti beenden?",
    exitMessage = "Bist du sicher, dass du beenden möchtest?",
    exitConfirm = "Beenden",
    exitCancel = "Abbrechen",
    copied = "Kopiert",
    decoded = "Dekodiert",
    platform = "Plattform",
    noDecoyNotes = "Keine Tarn-Notizen",

    darkThemeSubtitle = "Zwischen dunklem und hellem Erscheinungsbild wechseln",
    rootDetectionTitle = "Root-Erkennungswarnung",
    rootDetectionSubtitle = "Warnen, wenn das Gerät gerootet ist (weniger sicher)",
    language = "Sprache",
    selectLanguage = "Sprache auswählen",
    sidebarInstructions = "Anleitung",

    instructionsPromptTitle = "Sicherheitsanleitung lesen",
    instructionsPromptMessage = "Wir empfehlen dringend, die Sicherheitsanleitung vor der Nutzung der App zu lesen. Sie erklärt, wie Sie Ihre Daten vor Spyware, Keyloggern und Überwachung schützen.",
    instructionsPromptView = "Anleitung anzeigen",
    instructionsPromptSkip = "Überspringen",

    instructionsTitle = "Sicherheitsanleitung",
    instructionsIntro = "Sorgfältig lesen. Ihre Sicherheit hängt von der Befolgung dieser Schritte ab.",
    instructionsPasswordTitle = "1. Master-Passwort persönlich wählen",
    instructionsPasswordDetails = "Stellen Sie beim Erstellen Ihres Master-Passworts sicher, dass niemand zusieht. Schauen Sie nicht auf den Bildschirm, wenn Kameras in der Nähe sind. Verwenden Sie Groß- und Kleinbuchstaben, Zahlen und Symbole. Mindestens 8 Zeichen — länger ist besser.",
    instructionsPaperTitle = "2. Auf Papier schreiben",
    instructionsPaperDetails = "Speichern Sie Ihr Passwort niemals digital (keine Screenshots, keine Notiz-App, keine Cloud). Schreiben Sie es auf Papier und bewahren Sie es an einem sicheren Ort auf. Wenn jemand Ihr Papier findet, braucht er immer noch Ihr Telefon. Wenn jemand Ihr Telefon bekommt, braucht er immer noch Ihr Papier.",
    instructionsNoDigitalTitle = "3. Passwörter nie digital speichern",
    instructionsNoDigitalDetails = "Speichern Sie Passwörter in keiner digitalen Form — keine Textdateien, keine Passwort-Manager, keine E-Mail-Entwürfe, keine Cloud-Notizen. Digitale Kopien können kopiert, gehackt oder beschlagnahmt werden. Nur Papier.",
    instructionsNoReadAloudTitle = "4. Passwort niemals laut aussprechen",
    instructionsNoReadAloudDetails = "Moderne Spyware kann das Mikrofon Ihres Telefons ohne sichtbare Anzeichen aktivieren. Sprechen Sie Ihr Passwort niemals aus. Tippen Sie es nie, während jemand die Tastenanschläge hören kann. Gehen Sie davon aus, dass Ihr Gerät immer mithört.",
    instructionsHowToEncryptTitle = "So verschlüsseln Sie eine Nachricht",
    instructionsHowToEncryptDetails = "Öffnen Sie den Tab Verschlüsseln → geben Sie Ihre Nachricht ein → geben Sie eine starke Passphrase ein (oder tippen Sie auf Schlüssel generieren) → tippen Sie auf Verschlüsseln. Kopieren Sie die Ausgabe sicher. Optional können Sie den verschlüsselten Text als URL tarnen.",
    instructionsHowToDecryptTitle = "So entschlüsseln Sie eine Nachricht",
    instructionsHowToDecryptDetails = "Wenn Sie eine getarnte URL erhalten haben: Fügen Sie sie im Tab Tarnung ein, wählen Sie die Plattform und tippen Sie auf Dekodieren. Wechseln Sie dann zum Tab Entschlüsseln, fügen Sie den extrahierten Text ein, geben Sie den Schlüssel ein und tippen Sie auf Entschlüsseln. Wenn Sie den rohen verschlüsselten Text erhalten haben, fügen Sie ihn direkt im Tab Entschlüsseln ein.",
    instructionsMultiUserTitle = "Mehrbenutzer-Verschlüsselung",
    instructionsMultiUserDetails = "Wenn zwei oder mehr Personen verschlüsselte Nachrichten austauschen wollen: Treffen Sie sich persönlich, um die Passphrase gemeinsam zu erstellen. Jede Person schreibt sie auf Papier und bewahrt sie extrem sicher auf. Die Passphrase darf NIEMALS digital gesendet werden — nicht per SMS, Messenger, E-Mail oder Cloud. Nur das verschlüsselte Ergebnis darf das Gerät verlassen.",
    instructionsMultiUserFriends = "Verschlüsselung mit Freunden & Familie teilen",
    instructionsMultiUserFriendsDetails = "Trefft euch persönlich für eine gemeinsame Passphrase. Jeder schreibt sie auf Papier — nie in eine App tippen. Nutze das Verschlüsselungs-Werkzeug, dann teile nur die verschlüsselte Ausgabe (Text/Link) über einen Chat. Der Empfänger entschlüsselt mit derselben Passphrase.",
    instructionsCheckWebsite = "🔁 Updates prüfen: Besuche regelmäßig unsere Website für neue Versionen:\nhttps://cyberboy161.github.io/Taybeti/",
    instructionsMistakesTitle = "Häufige Fehler, die Sie vermeiden sollten",
    instructionsMistake1 = "❌ Dasselbe Passwort für mehrere Notizen oder Konten verwenden",
    instructionsMistake2 = "❌ Schlüssel in Cloud-Notizen, E-Mails oder Messaging-Apps speichern",
    instructionsMistake3 = "❌ Passwörter an öffentlichen Orten mit Kameras oder neugierigen Blicken eingeben",
    instructionsMistake4 = "❌ Kurze, wörterbuchbasierte oder vorhersehbare Passwörter verwenden",
    instructionsWarningTitle = "⚠️ Wichtige Warnungen",
    instructionsWarning1 = "Teilen Sie Ihr Master-Passwort NIEMALS mit jemandem — nicht einmal mit Support oder Strafverfolgungsbehörden",
    instructionsWarning2 = "Wenn Sie Ihr Passwort vergessen, können Ihre Daten NICHT wiederhergestellt werden — es gibt keine Hintertür",
    instructionsWarning3 = "Nach 5 falschen Versuchen wird eine 30-Sekunden-Sperre aktiviert — dies verhindert Brute-Force-Angriffe",
)

val soraniStrings = englishStrings.copy(
    continueBtn = "به‌رده‌وام بوون",
    cancel = "پاشگه‌زبوونه‌وه‌",
    copy = "له‌بهرگرتنه‌وه‌",
    paste = "لکاندن",
    edit = "ده‌ستکاری",
    delete = "سڕینه‌وه‌",
    save = "پاشه‌که‌وت کردن",
    back = "گه‌ڕانه‌وه‌",
    confirm = "پشتڕاست کردنەوە",
    ok = "باش",
    unlock = "کردنه‌وه‌",
    encrypt = "کۆدکردن",
    decrypt = "کۆدکردنه‌وه‌",
    chooseLanguage = "زمانی خۆت هه‌ڵبژێره‌",
    langSubtitle = "Zimanê xwe hilbijêre",
    loginTitle = "کردنه‌وه‌ی گه‌نجینه‌",
    masterPassword = "وشه‌ی نهێنی سەرەکی",
    loginButton = "کردنه‌وه‌",
    forgotPassword = "وشه‌ی نهێنیت له‌بیر کردووه‌؟",
    resetWarning = "هه‌موو داتاکانت لەدەست دەدەیت. دڵنیایت؟",
    setupTitle = "به‌خێربێیت بۆ Taybeti",
    setupSubtitle = "گه‌نجینه‌که‌ت ڕێک بخە",
    setupCreatePassword = "وشه‌ی نهێنی سەرەکی دروست بکه‌",
    setupConfirmPassword = "وشه‌ی نهێنی دووپات بکه‌ره‌وه‌",
    setupCreateBtn = "گه‌نجینه‌ دروست بکه‌",
    setupPasswordMismatch = "وشه‌ی نهێنیه‌کان یەک ناگرن",
    setupPasswordShort = "لانی کەم ٨ پیت",
    setupSecureVault = "گه‌نجینه‌ی پارێزراو",
    setupDecoyVault = "گه‌نجینه‌ی ساختە",
    setupEnableDecoy = "گه‌نجینه‌ی ساختە چالاک بکە",
    setupDecoyPassword = "وشه‌ی نهێنی ساختە",
    setupDecoyHint = "وشه‌ی نهێنی بۆ گه‌نجینه‌ی ساختە (ئارەزوومەندانە)",
    allNotes = "هه‌موو تێبینییەکان",
    favorites = "دڵخوازەکان",
    decoyNotes = "تێبینییە ساختەکان",
    noNotes = "هێشتا تێبینی نییە",
    createNote = "دروستکردنی تێبینی",
    searchNotes = "گه‌ڕان له‌ تێبینییەکان...",
    encryptedNote = "کۆدکراو",
    noteModified = "دەستکاری کراوە",
    noFavorites = "هێشتا دڵخواز نییە",
    editNote = "دەستکاری تێبینی",
    newNote = "تێبینی نوێ",
    noteTitle = "ناونیشانی تێبینی",
    noteContent = "ناوه‌ڕۆکی تێبینی",
    noteKey = "کلیلی تێبینی",
    createKey = "دروستکردنی کلیل",
    enterKeyToDecrypt = "کلیل بنووسه‌ بۆ کردنەوەی تێبینی",
    encryptedMessage = "پەیامی کۆدکراو:",
    disguisedUrl = "بەستەری خۆگونجێنراو",
    disguiseAs = "خۆگونجاندن وه‌ک",
    disguiseAsLink = "خۆگونجاندن وه‌ک بەستەری هاوبەشکراو",
    generateKey = "دروستکردنی کلیلی پارێزراو",
    keyRequired = "پێویستیت بە کلیلە",
    keyTooShort = "کلیل زۆر کورتە (کەمترین ٨ پیت)",
    wrongKey = "کلیلی هەڵە",
    minChars = "کەمترین ٨ پیت",
    keysMatch = "کلیلەکان یەک ناگرن",
    discardNoteTitle = "تێبینییەکە لەناو ببەیت؟",
    discardNoteMsg = "ناوه‌ڕۆکی پاشه‌که‌وت نەکراوت هەیە. سەرەتا کۆدی بکە بۆ پاشه‌که‌وت کردن، یان گۆڕانکارییەکان لەناو ببە.",
    stay = "مانەوە",
    discard = "لەناوبردن",
    enterNoteKey = "کلیلی تێبینی بنووسە",
    reEnterKeyToUnlock = "دووبارە کلیل بنووسه‌ بۆ کردنەوە و دەستکاری تێبینی.",
    encryptNote = "کۆدکردنی تێبینی",
    encryptDecryptTitle = "کۆدکردن / کردنەوە",
    encryptTab = "کۆدکردن",
    decryptTab = "کردنەوە",
    decoyTab = "خۆگونجاندن",
    plaintext = "دەقی ئاشکرا",
    encryptedBlob = "دەقی کۆدکراو",
    encryptionKey = "کلیلی کۆدکردن",
    encrypting = "کۆد دەکرێت...",
    decrypting = "دەکرێتەوە...",
    encryptedOutput = "دەرئەنجامی کۆدکراو:",
    decrypted = "کراوەتەوە:",
    encryptFailed = "کۆدکردن سەرکەوتوو نەبوو",
    decryptFailed = "کردنەوە سەرکەوتوو نەبوو (کلیلی هەڵە یان داتای تێکچوو)",
    invalidBlob = "شێوازی دەق نادروستە",
    pasteUrlFirst = "سەرەتا بەستەرێک لکێنە",
    invalidUrl = "بەستەری نادروست بۆ پلاتفۆرمی دیاریکراو",
    extractedBlob = "دەقی کۆدکراوی دەرهێنراو:",
    decode = "کردنەوە",
    switchToDecrypt = "بڕۆ بۆ تابى کردنەوە، دەقەکە لکێنە و کلیل بنووسە.",
    disabledUrlPasteHint = "بەستەرێکی خۆگونجێنراو لکێنە بۆ دەرهێنانی پەیامی کۆدکراو.",
    decoyHint = "بەستەرێکی خۆگونجێنراو لکێنە بۆ دەرهێنانی پەیامی کۆدکراو.",
    trash = "سەبەتە",
    noTrash = "سەبەتە بەتاڵە",
    restore = "گه‌ڕاندنه‌وه‌",
    deleteForever = "بۆ هەمیشە بیسڕەوە",
    settings = "ڕێکخستنەکان",
    darkTheme = "ڕووکاری تاریک",
    biometricLock = "قفڵی بایۆمەتریک",
    changePassword = "گۆڕینی وشه‌ی نهێنی",
    currentPassword = "وشه‌ی نهێنی ئێستا",
    newPassword = "وشه‌ی نهێنی نوێ",
    confirmNewPassword = "دووپاتکردنەوەی وشه‌ی نهێنی نوێ",
    passwordChanged = "وشه‌ی نهێنی گۆڕدرا",
    passwordChangedSubtitle = "ئەپەکە بەستارت بکەرەوە بۆ بەکارهێنانی وشه‌ی نهێنی نوێ. تێبینییەکانت پارێزراون.",
    autoLockOff = "ناچالاک",
    autoLock1min = "١ خولەک",
    autoLock5min = "٥ خولەک",
    autoLock15min = "١٥ خولەک",
    autoLock30min = "٣٠ خولەک",
    autoLock1hr = "١ کاتژمێر",
    settingsDecoySetup = "دروستکردنی وشه‌ی نهێنی ساختە",
    settingsDecoySubtitle = "وشه‌ی نهێنی ساختە زیاد بکە بۆ شاراوەکردنی داتا ڕاستییەکان",
    autoLockTimeout = "کاتی قفڵکردنی ئۆتۆماتیکی",
    securityLevel = "ئاستی ئاسایش",
    exportImport = "هەناردە / هاوردە",
    exportTitle = "هەناردە",
    importTitle = "هاوردە",
    exportPassword = "وشه‌ی نهێنی هەناردە",
    exportFile = "په‌ڕگه‌ی هەناردە",
    importFile = "په‌ڕگه‌ی هاوردە",
    exportSuccess = "بە سەرکەوتویی هەناردە کرا",
    importSuccess = "بە سەرکەوتویی هاوردە کرا",
    about = "ده‌رباره‌ی",
    aboutVersion = "وەشان",
    aboutDescription = "ئەپێکی پارێزراوی تێبینی بە کۆدکردنی ئاستی سەربازی.",
    aboutLicense = "مۆڵەتی MIT",
    aboutTechStack = "تەکنەلۆژیای بەکارهاتوو:\n• Kotlin + Jetpack Compose\n• AES-256-GCM شیفرکردن\n• Argon2id کلیل درووستکردن (64MB)\n• Room داتابەیس (SQLCipher)\n• بێ مۆڵەتی ئینتەرنێت\n• بێ Google Play Services",
    aboutThreatModelTitle = "مۆدێلی هەڕەشە",
    aboutThreatModel = "پاراستن لە:\n• دەستبەسەرداگرتنی فیزیکی (شیفرکراو)\n• ئەپی زیانبەخش (بێ IPC، FLAG_SECURE)\n• کیلاگەری تەختەکلیل (تەختەکلیلی تایبەت)\n• وێنەگرتنی شاشە (FLAG_SECURE)\n• دەرهێنانی باکئەپی ئەندرۆید (ناچالاک)\n• دزەکردنی سینکی هەور (بێ ئینتەرنێت)\n• دەرهێنانی کلیلی گوگڵ/سیستەم (بێ Keystore)\n\nسنووردارکردنەکان:\n• پاراستن لە کێرنەلی سیستەمی تێکچوو نییە\n• پاراستن لە کیلاگەری ڕەقەکاڵا نییە\n• RAM دەقی ڕوونی تێدایە کاتێک نۆت کراوەیە",
    aboutCommunityTitle = "بەشداری کۆمەڵگەکەم بکە",
    sidebarSecureVault = "گه‌نجینه‌ی پارێزراو",
    sidebarDecoyVault = "گه‌نجینه‌ی ساختە",
    sidebarAllNotes = "هه‌موو تێبینییەکان",
    sidebarFavorites = "دڵخوازەکان",
    sidebarEncryptDecrypt = "کۆدکردن/کردنەوە",
    sidebarTrash = "سەبەتە",
    sidebarSettings = "ڕێکخستنەکان",
    sidebarExportImport = "هەناردە/هاوردە",
    sidebarAbout = "ده‌رباره‌ی",
    sidebarLockVault = "داخستنی گه‌نجینه‌",
    exitTitle = "دەرچوون له‌ Taybeti؟",
    exitMessage = "دڵنیایت دەتەوێت دەربچیت؟",
    exitConfirm = "دەرچوون",
    exitCancel = "پاشگه‌زبوونه‌وه‌",
    copied = "له‌بەر گیرایەوە",
    decoded = "کرایەوە",
    platform = "پلاتفۆرم",
    noDecoyNotes = "هیچ تێبینییه‌کی ساختە نییە",

    darkThemeSubtitle = "گۆڕینی نێوان دەرکەوتنی تاریک و ڕووناک",
    rootDetectionTitle = "ئاگاداری دۆزینەوەی ڕووت",
    rootDetectionSubtitle = "ئاگاداربە ئەگەر ئامێرەکە ڕووتکرابێت (کەمتر پارێزراوە)",
    language = "زمان",
    selectLanguage = "زمان هەڵبژێرە",
    sidebarInstructions = "ڕێنماییەکان",

    instructionsPromptTitle = "ڕێنماییەکانی ئاسایش بخوێنەرەوە",
    instructionsPromptMessage = "بەتوندی پێشنیار دەکەین ڕێنماییەکانی ئاسایش بخوێنیتەوە پێش بەکارهێنانی ئەپەکە. ئەوان ڕوونی دەکەنەوە چۆن داتاکەت لە سپایوێر و کیلاگەر و چاودێری بپارێزیت.",
    instructionsPromptView = "ڕێنماییەکان ببینە",
    instructionsPromptSkip = "پەڕاندن",

    instructionsTitle = "ڕێنماییەکانی ئاسایش",
    instructionsIntro = "بەوردی بخوێنەرەوە. ئاسایشی تۆ بەندە بە پەیڕەوکردنی ئەم هەنگاوانە.",
    instructionsPasswordTitle = "١. تێپەڕەوشەی سەرەکی بە شێوەیەکی کەسی هەڵبژێرە",
    instructionsPasswordDetails = "کاتێک تێپەڕەوشەی سەرەکی درووست دەکەیت، دڵنیابە کە کەس سەیری ناکات. سەیری شاشە مەکە کاتێک تایپ دەکەیت ئەگەر کامێرا لە نزیکەوە هەیە. پیتی گەورە و بچووک، ژمارە و هێما بەکاربهێنە. کەمترین ٨ پیت — درێژتر باشترە.",
    instructionsPaperTitle = "٢. لەسەر کاغەز بینووسە",
    instructionsPaperDetails = "هەرگیز تێپەڕەوشەت بە شێوەی دیجیتاڵی مەپارێزە (بێ وێنەی شاشە، بێ ئەپی تێبینی، بێ هەور). لەسەر کاغەزی فیزیکی بینووسە و لە شوێنێکی پارێزراودا دایبنێ. ئەگەر کەسێک کاغەزەکەت بدۆزێتەوە، هێشتا مۆبایلەکەت پێویستە. ئەگەر کەسێک مۆبایلەکەت ببات، هێشتا کاغەزەکەت پێویستە.",
    instructionsNoDigitalTitle = "٣. هەرگیز تێپەڕەوشە بە شێوەی دیجیتاڵی مەپارێزە",
    instructionsNoDigitalDetails = "تێپەڕەوشەکان بە هیچ شێوەیەکی دیجیتاڵی مەپارێزە — بێ فایلی دەقی، بێ بەڕێوەبەری تێپەڕەوشە، بێ ڕەشنووسی ئیمەیڵ، بێ تێبینی هەوری. کۆپی دیجیتاڵی دەکرێ کۆپی بکرێت، هاک بکرێت یان دەستبەسەر بکرێت. تەنها کاغەز.",
    instructionsNoReadAloudTitle = "٤. هەرگیز تێپەڕەوشەت بە دەنگی بەرز مەخوێنەرەوە",
    instructionsNoReadAloudDetails = "سپایوێری مۆدێرن دەتوانێت مایکرۆفۆنی مۆبایلەکەت بەبێ نیشانەی بینراو چالاک بکات. هەرگیز تێپەڕەوشەت بە دەنگ مەڵێ. هەرگیز تایپی مەکە کاتێک کەسێک دەنگی پەنجەکانت دەبیستێت. وادابنێ کە ئامێرەکەت هەمیشە گوێ دەگرێت.",
    instructionsHowToEncryptTitle = "چۆنیەتی کۆدکردنی نامەیەک",
    instructionsHowToEncryptDetails = "هەڵبژاردەی کۆدکردن بکەرەوە → نامەکەت تایپ بکە → تێپەڕەوشەیەکی بەهێز تایپ بکە (یان کلیلی درووستکردن لێبدە) → کۆدکردن لێبدە. ئەنجامەکە بە سەلامەتی کۆپی بکە. بە ویستی خۆت دەتوانی دەقی کۆدکراو وەک URL بشاریتەوە.",
    instructionsHowToDecryptTitle = "چۆنیەتی شی کردنەوەی نامەیەک",
    instructionsHowToDecryptDetails = "ئەگەر URLێکی شاراوەت وەرگرت: لە هەڵبژاردەی شاردنەوە دایبنێ، پلاتفۆرمەکە هەڵبژێرە و شی کردنەوە لێبدە. دواتر بڕۆ بۆ هەڵبژاردەی شی کردنەوە، دەقی دەرهێنراو دایبنێ، کلیلەکە تایپ بکە و شی کردنەوە لێبدە. ئەگەر دەقی کۆدکراوی خاو وەرگرت، ڕاستەوخۆ لە هەڵبژاردەی شی کردنەوە دایبنێ.",
    instructionsMultiUserTitle = "ڕێنمایی بۆ چەند بەکارهێنەر",
    instructionsMultiUserDetails = "کاتێک دوو کەس یان زیاتر دەیانەوێت نامەی کریپتۆکراو ئاڵوگۆڕ بکەن: بەیەکەوە بە شێوەیەکی فیزیکی کۆببنەوە و پەڕەوشە بەیەکەوە دروست بکەن. هەر کەسێک لەسەر کاغەز بینووسێت و لە شوێنێکی زۆر پارێزراودا بیپارێزێت. نابێت پەڕەوشە هەرگیز بە شێوەی دیجیتاڵ بنێردرێت - نە لە ڕێگەی SMS، نامەنێر، ئیمەیڵ یان هەوری ئەلیکترۆنییەوە. تەنها دەرئەنجامی کریپتۆکراو دەبێت لە ئامێرەکە دەربچێت.",
    instructionsMultiUserFriends = "ڕێنمایی بۆ هاوڕێ و خێزان",
    instructionsMultiUserFriendsDetails = "بە شێوەی فیزیکی کۆببنەوە و پەڕەوشە دیاری بکەن. هر که‌س له‌سه‌ر کاغه‌ز بینووسێت. ئامرازی کریپتۆ بەکاربهێنە، دواتر تەنها دەرئەنجامی کریپتۆکراو بنێرە.",
    instructionsCheckWebsite = "🔁 بۆ نوێکاری: بەردەوام سه‌ردانی وێبسایته‌که‌مان بکه بۆ وه‌شانی نوێ:\nhttps://cyberboy161.github.io/Taybeti/",
    instructionsMistakesTitle = "هەڵە باوەکان کە دەبێت خۆتی لێ بەدوور بگریت",
    instructionsMistake1 = "❌ بەکارهێنانی هەمان تێپەڕەوشە بۆ چەندین تێبینی یان ئەژمێر",
    instructionsMistake2 = "❌ پاشەکەوتکردنی کلیلەکان لە تێبینی هەوری، ئیمەیڵ یان ئەپی نامە",
    instructionsMistake3 = "❌ تایپکردنی تێپەڕەوشە لە شوێنی گشتیدا کە کامێرا یان چاودێری شان هەیە",
    instructionsMistake4 = "❌ بەکارهێنانی تێپەڕەوشەی کورت، فەرهەنگی یان پێشبینیکراو",
    instructionsWarningTitle = "⚠️ ئاگاداری گرنگ",
    instructionsWarning1 = "هەرگیز تێپەڕەوشەی سەرەکی لەگەڵ کەسدا هاوبەش مەکە — تەنانەت لەگەڵ پشتگیری یان دەسەڵاتی یاسایی",
    instructionsWarning2 = "ئەگەر تێپەڕەوشەکەت لەبیر چوو، داتاکەت ناتوانرێت وەربگیرێتەوە — هیچ دەرچەیەکی پشتەوە نییە",
    instructionsWarning3 = "دوای ٥ هەوڵی هەڵە، قفڵێکی ٣٠ چرکەیی چالاک دەبێت — ئەمە ڕێگری لە هێرشی برووت-فۆرس دەکات",
)

val kurmanjiStrings = englishStrings.copy(
    continueBtn = "Bidomîne",
    cancel = "Betalke",
    copy = "Kopî bike",
    paste = "Bizeliqîne",
    edit = "Biguhêre",
    delete = "Jê bibe",
    save = "Tomar bike",
    back = "Vegere",
    confirm = "Pesend bike",
    ok = "Baş",
    unlock = "Veke",
    encrypt = "Şîfre bike",
    decrypt = "Şîfre veke",
    chooseLanguage = "Zimanê xwe hilbijêre",
    langSubtitle = "Zimanê xwe hilbijêre",
    loginTitle = "Xezîneyê veke",
    masterPassword = "Şîfreya sereke",
    loginButton = "Veke",
    forgotPassword = "Şîfreya xwe ji bîr kir?",
    resetWarning = "Hemû daneyên te winda dibin. Tu piştrast î?",
    setupTitle = "Bi xêr hatî Taybeti",
    setupSubtitle = "Xezîneya xwe saz bike",
    setupCreatePassword = "Şîfreya sereke çêke",
    setupConfirmPassword = "Şîfreya sereke dubare bike",
    setupCreateBtn = "Xezîneyê çêke",
    setupPasswordMismatch = "Şîfre li hev nakin",
    setupPasswordShort = "Herî kêm 8 tîp",
    setupSecureVault = "Xezîneya ewle",
    setupDecoyVault = "Xezîneya sexte",
    setupEnableDecoy = "Xezîneya sexte çalak bike",
    setupDecoyPassword = "Şîfreya sexte",
    setupDecoyHint = "Şîfreyek ji bo xezîneya sexte (ne mecbûrî)",
    allNotes = "Hemû not",
    favorites = "Bijare",
    decoyNotes = "Notên sexte",
    noNotes = "Hê tu not tuneye",
    createNote = "Not çêke",
    searchNotes = "Di notan de bigere...",
    encryptedNote = "Şîfrekirî",
    noteModified = "Hate guhertin",
    noFavorites = "Hê tu bijare tuneye",
    editNote = "Notê biguhêre",
    newNote = "Nota nû",
    noteTitle = "Sernavê notê",
    noteContent = "Naveroka notê",
    noteKey = "Kilîla notê",
    createKey = "Kilîlê çêke",
    enterKeyToDecrypt = "Kilîlê binivîse ji bo vekirina notê",
    encryptedMessage = "Peyama şîfrekirî:",
    disguisedUrl = "URL-ya kamûflekirî",
    disguiseAs = "Kamûfle wek",
    disguiseAsLink = "Kamûfle wek lînka parvekirî",
    generateKey = "Kilîla ewle çêke",
    keyRequired = "Kilîl pêwîst e",
    keyTooShort = "Kilîl pir kurt e (herî kêm 8 tîp)",
    wrongKey = "Kilîla şaş",
    minChars = "Herî kêm 8 tîp",
    keysMatch = "Kilîl li hev nakin",
    discardNoteTitle = "Notê biavêjî?",
    discardNoteMsg = "Naveroka neqeydkirî heye. Pêşî şîfre bike ji bo qeydkirinê, yan guhertinan biavêje.",
    stay = "Bimîne",
    discard = "Biavêje",
    enterNoteKey = "Kilîla notê binivîse",
    reEnterKeyToUnlock = "Dîsa kilîlê binivîse ji bo vekirin û guherandina notê.",
    encryptNote = "Notê şîfre bike",
    encryptDecryptTitle = "Şîfre kirin / Vekirin",
    encryptTab = "Şîfre bike",
    decryptTab = "Veke",
    decoyTab = "Kamûfle",
    plaintext = "Nivîsa vekirî",
    encryptedBlob = "Nivîsa şîfrekirî",
    encryptionKey = "Kilîla şîfrekirinê",
    encrypting = "Şîfre dibe...",
    decrypting = "Vedibe...",
    encryptedOutput = "Encama şîfrekirî:",
    decrypted = "Vebû:",
    encryptFailed = "Şîfre kirin serneket",
    decryptFailed = "Vekirin serneket (kilîla şaş an daneyên xirab)",
    invalidBlob = "Formata nivîsê nederbasdar e",
    pasteUrlFirst = "Pêşî URL-yek bizeliqîne",
    invalidUrl = "URL ji bo platforma hilbijartî nederbasdar e",
    extractedBlob = "Nivîsa şîfrekirî ya derxistî:",
    decode = "Deşîfre bike",
    switchToDecrypt = "Here taba Vekirinê, nivîsê bizeliqîne û kilîla xwe binivîse.",
    disabledUrlPasteHint = "URL-ya kamûflekirî bizeliqîne ji bo derxistina peyama şîfrekirî.",
    decoyHint = "URL-ya kamûflekirî bizeliqîne ji bo derxistina peyama şîfrekirî.",
    trash = "Sêlê",
    noTrash = "Sêl vala ye",
    restore = "Vegerîne",
    deleteForever = "Her û her jê bibe",
    settings = "Mîhengan",
    darkTheme = "Moda tarî",
    biometricLock = "Qefla biyometrîk",
    changePassword = "Şîfreyê biguhêre",
    currentPassword = "Şîfreya niha",
    newPassword = "Şîfreya nû",
    confirmNewPassword = "Şîfreya nû dubare bike",
    passwordChanged = "Şîfre hat guhertin",
    passwordChangedSubtitle = "Sepanê ji nû ve bidestpêke ji bo şîfreya nû. Notên te ewle ne.",
    autoLockOff = "Girtî",
    autoLock1min = "1 deqîqe",
    autoLock5min = "5 deqîqe",
    autoLock15min = "15 deqîqe",
    autoLock30min = "30 deqîqe",
    autoLock1hr = "1 saet",
    settingsDecoySetup = "Şîfreya sexte saz bike",
    settingsDecoySubtitle = "Şîfreyeke sexte lê zêde bike ji bo veşartina daneyên rastîn",
    autoLockTimeout = "Dema qeflbûna otomatîk",
    securityLevel = "Asta ewlehiyê",
    exportImport = "Derxistin / Anîn",
    exportTitle = "Derxe",
    importTitle = "Bîne",
    exportPassword = "Şîfreya derxistinê",
    exportFile = "Pelê derxistinê",
    importFile = "Pelê anînê",
    exportSuccess = "Bi serkeftî hat derxistin",
    importSuccess = "Bi serkeftî hat anîn",
    about = "Derbar",
    aboutVersion = "Versiyon",
    aboutDescription = "Sepaneka ewle ya notan bi şîfrekirina asta leşkerî.",
    aboutLicense = "Lîsansa MIT",
    aboutTechStack = "Stacka Teknîkî:\n• Kotlin + Jetpack Compose\n• AES-256-GCM şîfrekirin\n• Argon2id kilîl çêkirin (64MB)\n• Room databas (SQLCipher)\n• Bê destûra înternetê\n• Bê Google Play Services",
    aboutThreatModelTitle = "Modela Tehdîdê",
    aboutThreatModel = "Diparêze li dijî:\n• Desteserkirina fizîkî (şîfrekirî)\n• Sepanên xirab (bê IPC, FLAG_SECURE)\n• Tomarkirina klavyeyê (klavyeya taybet)\n• Wêneyê ekranê (FLAG_SECURE)\n• Derxistina backupa Android (neçalak)\n• Hizkirina syncê ewran (bê înternet)\n• Derxistina kilîlên Google/OS (bê Keystore)\n\nSînorkirin:\n• Li dijî kernela OS-ê ya têkçûyî naparêze\n• Li dijî keyloggerên hardware naparêze\n• RAM dema not vekirî ye deqa sade dihewîne",
    aboutCommunityTitle = "Tevlî civata min bibe",
    sidebarSecureVault = "Xezîneya ewle",
    sidebarDecoyVault = "Xezîneya sexte",
    sidebarAllNotes = "Hemû not",
    sidebarFavorites = "Bijare",
    sidebarEncryptDecrypt = "Şîfre/Vekirin",
    sidebarTrash = "Sêl",
    sidebarSettings = "Mîhengan",
    sidebarExportImport = "Derxistin/Anîn",
    sidebarAbout = "Derbar",
    sidebarLockVault = "Xezîneyê kilît bike",
    exitTitle = "Ji Taybeti derkeve?",
    exitMessage = "Tu piştrast î dixwazî derkevî?",
    exitConfirm = "Derkeve",
    exitCancel = "Betalke",
    copied = "Hat kopîkirin",
    decoded = "Hat deşîfrekirin",
    platform = "Platform",
    noDecoyNotes = "Notên sexte tunene",

    darkThemeSubtitle = "Guhertina navbera xuyanga tarî û ronahî",
    rootDetectionTitle = "Hişyariya Tesbîtkirina Root",
    rootDetectionSubtitle = "Hişyar bike eger amûr rootkirî be (kêmtir ewle)",
    language = "Ziman",
    selectLanguage = "Ziman hilbijêre",
    sidebarInstructions = "Rênimayî",

    instructionsPromptTitle = "Rênimayiyên ewlehiyê bixwîne",
    instructionsPromptMessage = "Em bi tundî pêşniyar dikin ku berî bikaranîna sepana, rênimayiyên ewlehiyê bixwînî. Ew rave dikin ka çawa daneyên xwe ji spyware, keylogger û çavdêriyê biparêzî.",
    instructionsPromptView = "Rênimayiyan bibîne",
    instructionsPromptSkip = "Bihêle",

    instructionsTitle = "Rênimayiyên Ewlehiyê",
    instructionsIntro = "Bi baldarî bixwîne. Ewlehiya te bi şopandina van gavan ve girêdayî ye.",
    instructionsPasswordTitle = "1. Şîfreya xwe ya sereke bi awayekî kesane hilbijêre",
    instructionsPasswordDetails = "Dema şîfreya xwe ya sereke çêdikî, piştrast be ku kes lê temaşe nake. Dema tîp dike, li ser ekranê mêze neke eger kamerayên nêzîk hebin. Tîpên mezin û biçûk, jimar û sembolan bikar bîne. Kêmtirîn 8 tîp — dirêjtir çêtir e.",
    instructionsPaperTitle = "2. Li ser kaxezê binivîse",
    instructionsPaperDetails = "Qet şîfreya xwe bi awayekî dîjîtal tomar neke (bê screenshots, bê sepana notan, bê ewr). Li ser kaxezeke fizîkî binivîse û li cihekî ewle bihêle. Eger kesek kaxezê te bibîne, hê jî telefona te pêwîst e. Eger kesek telefona te bibe, hê jî kaxezê te pêwîst e.",
    instructionsNoDigitalTitle = "3. Qet şîfreyan bi awayekî dîjîtal tomar neke",
    instructionsNoDigitalDetails = "Şîfreyan bi tu awayekî dîjîtal tomar neke — bê dosyeyên nivîsê, bê rêveberên şîfreyan, bê pêşnivîsên e-nameyê, bê notên ewran. Kopiyên dîjîtal dikarin bên kopîkirin, hackkirin an desteserkirin. Tenê kaxez.",
    instructionsNoReadAloudTitle = "4. Qet şîfreya xwe bi deng nexwîne",
    instructionsNoReadAloudDetails = "Spywareyên nûjen dikarin mîkrofona telefona te bêyî nîşanên xuyabar çalak bikin. Qet şîfreya xwe bi deng nebêje. Qet dema ku kes dikare dengê tikandinê bibihîze tîp neke. Wisa bihesibîne ku cîhaza te her tim guhdarî dike.",
    instructionsHowToEncryptTitle = "Çawa peyamekê şîfre bikî",
    instructionsHowToEncryptDetails = "Tabê Şîfrekirin veke → peyama xwe binivîse → şîfreyeke bihêz têxe (an Generate Key bitikîne) → Şîfrekirin bitikîne. Derketinê bi ewlehî kopî bike. Vebijarkî tu dikarî nivîsa şîfrekirî wek URL-kê veşêrî.",
    instructionsHowToDecryptTitle = "Çawa peyamekê deşîfre bikî",
    instructionsHowToDecryptDetails = "Eger te URL-yeke veşartî wergirt: wê di Tabê Veşartinê de bizeliqîne, platformê hilbijêre û Deşîfrekirin bitikîne. Paşê here Tabê Deşîfrekirinê, nivîsa derxistî bizeliqîne, kilîlê têxe û Deşîfrekirin bitikîne. Eger te nivîsa şîfrekirî ya xav wergirt, rasterast di Tabê Deşîfrekirinê de bizeliqîne.",
    instructionsMultiUserTitle = "Şîfrekirina Pir-Bikarhêner",
    instructionsMultiUserDetails = "Dema du an zêdetir kes dixwazin peyamên şîfrekirî biguherînin: Bi hev re fizîkî bicivin û peyva şîfreyê bi hev re çêbikin. Her kes wê li ser kaxezê binivîsîne û li cihekî pir ewle biparêze. Divê peyva şîfreyê QET bi awayekî dîjîtal neyê şandin — ne bi SMS, Messenger, e-name an ewr. Tenê encama şîfrekirî dikare ji cîhazê derkeve.",
    instructionsMultiUserFriends = "Şîfrekirinê bi Heval û Malbatê re Parve Bike",
    instructionsMultiUserFriendsDetails = "Bi hev re fizîkî bicivin û peyva şîfreyê saz bikin. Her kes li ser kaxezê binivîsîne. Amûra Şîfrekirinê bikar bîne, tenê encama şîfrekirî bişîne.",
    instructionsCheckWebsite = "🔁 Ji bo nûvekirinan: Bi rêkûpêk serdana malpera me bike ji bo versiyonên nû:\nhttps://cyberboy161.github.io/Taybeti/",
    instructionsMistakesTitle = "Xeletiyên hevpar ku divê jê dûr bikevî",
    instructionsMistake1 = "❌ Bikaranîna heman şîfreyê ji bo gelek not an hesaban",
    instructionsMistake2 = "❌ Tomarkirina kilîlan di notên ewran, e-nameyê an sepanên mesajan de",
    instructionsMistake3 = "❌ Tîpkirina şîfreyan li cihên giştî yên bi kamera an kesên ku li milê te dinihêrin",
    instructionsMistake4 = "❌ Bikaranîna şîfreyên kurt, ferhengî an pêşbînîkirî",
    instructionsWarningTitle = "⚠️ Hişyariyên Girîng",
    instructionsWarning1 = "QET şîfreya xwe ya sereke bi kesî re parve neke — ne bi piştgiriyê re jî, ne bi dadgehê re jî",
    instructionsWarning2 = "Eger tu şîfreya xwe ji bîr bikî, daneyên te NAYÊN vegerandin — tu deriyê paş ve tune",
    instructionsWarning3 = "Piştî 5 hewildanên şaş, qilfeke 30-saniyeyî çalak dibe — ev êrîşên brute-force asteng dike",
)

val turkishStrings = englishStrings.copy(
    continueBtn = "Devam",
    cancel = "İptal",
    copy = "Kopyala",
    paste = "Yapıştır",
    edit = "Düzenle",
    delete = "Sil",
    save = "Kaydet",
    back = "Geri",
    confirm = "Onayla",
    ok = "Tamam",
    unlock = "Kilidi Aç",
    encrypt = "Şifrele",
    decrypt = "Şifreyi Çöz",
    chooseLanguage = "Dilini seç",
    langSubtitle = "Zimanê xwe hilbijêre",
    loginTitle = "Kasayı Aç",
    masterPassword = "Ana Parola",
    loginButton = "Kilidi Aç",
    forgotPassword = "Parolamı Unuttum?",
    resetWarning = "Tüm verilerini kaybedeceksin. Emin misin?",
    setupTitle = "Taybeti'ye Hoş Geldin",
    setupSubtitle = "Güvenli kasanı oluştur",
    setupCreatePassword = "Ana Parola Oluştur",
    setupConfirmPassword = "Ana Parolayı Onayla",
    setupCreateBtn = "Kasa Oluştur",
    setupPasswordMismatch = "Parolalar eşleşmiyor",
    setupPasswordShort = "En az 8 karakter",
    setupSecureVault = "Güvenli Kasa",
    setupDecoyVault = "Tuzak Kasa",
    setupEnableDecoy = "Tuzak kasayı etkinleştir",
    setupDecoyPassword = "Tuzak Parola",
    setupDecoyHint = "Tuzak kasa için bir parola gir (isteğe bağlı)",
    allNotes = "Tüm Notlar",
    favorites = "Favoriler",
    decoyNotes = "Tuzak Notlar",
    noNotes = "Henüz not yok",
    createNote = "Not Oluştur",
    searchNotes = "Notlarda ara...",
    encryptedNote = "Şifreli",
    noteModified = "Düzenlendi",
    noFavorites = "Henüz favori yok",
    editNote = "Notu Düzenle",
    newNote = "Yeni Not",
    noteTitle = "Not başlığı",
    noteContent = "Not içeriği",
    noteKey = "Not anahtarı",
    createKey = "Anahtar Oluştur",
    enterKeyToDecrypt = "Notu çözmek için anahtarı girin",
    encryptedMessage = "Şifreli Mesaj:",
    disguisedUrl = "Gizlenmiş URL",
    disguiseAs = "Şu şekilde gizle",
    disguiseAsLink = "Paylaşılabilir bağlantı olarak gizle",
    generateKey = "Güvenli Anahtar Oluştur",
    keyRequired = "Anahtar gerekli",
    keyTooShort = "Anahtar çok kısa (en az 8 karakter)",
    wrongKey = "Yanlış anahtar",
    minChars = "En az 8 karakter",
    keysMatch = "Anahtarlar eşleşmiyor",
    discardNoteTitle = "Not silinsin mi?",
    discardNoteMsg = "Kaydedilmemiş içerik var. Kaydetmek için önce şifrele, ya da değişiklikleri sil.",
    stay = "Kal",
    discard = "Sil",
    enterNoteKey = "Not Anahtarını Gir",
    reEnterKeyToUnlock = "Notu açmak ve düzenlemek için anahtarı tekrar gir.",
    encryptNote = "Notu Şifrele",
    encryptDecryptTitle = "Şifrele / Çöz",
    encryptTab = "Şifrele",
    decryptTab = "Çöz",
    decoyTab = "Gizle",
    plaintext = "Düz metin",
    encryptedBlob = "Şifreli metin",
    encryptionKey = "Şifreleme anahtarı",
    encrypting = "Şifreleniyor...",
    decrypting = "Çözülüyor...",
    encryptedOutput = "Şifreli Çıktı:",
    decrypted = "Çözüldü:",
    encryptFailed = "Şifreleme başarısız",
    decryptFailed = "Çözme başarısız (yanlış anahtar veya bozuk veri)",
    invalidBlob = "Geçersiz metin formatı",
    pasteUrlFirst = "Önce bir URL yapıştır",
    invalidUrl = "Seçilen platform için geçersiz URL",
    extractedBlob = "Çıkarılan şifreli metin:",
    decode = "Çöz",
    switchToDecrypt = "Çöz sekmesine geç, metni yapıştır ve anahtarını gir.",
    disabledUrlPasteHint = "Şifreli mesajı çıkarmak için gizlenmiş bir URL yapıştır.",
    decoyHint = "Şifreli mesajı çıkarmak için gizlenmiş bir URL yapıştır.",
    trash = "Çöp Kutusu",
    noTrash = "Çöp kutusu boş",
    restore = "Geri Yükle",
    deleteForever = "Kalıcı Olarak Sil",
    settings = "Ayarlar",
    darkTheme = "Karanlık Tema",
    biometricLock = "Biyometrik Kilit",
    changePassword = "Parolayı Değiştir",
    currentPassword = "Mevcut Parola",
    newPassword = "Yeni Ana Parola",
    confirmNewPassword = "Yeni Parolayı Onayla",
    passwordChanged = "Parola Değiştirildi",
    passwordChangedSubtitle = "Yeni parolanızı kullanmak için uygulamayı yeniden başlatın. Notlarınız güvende.",
    autoLockOff = "Kapalı",
    autoLock1min = "1 dakika",
    autoLock5min = "5 dakika",
    autoLock15min = "15 dakika",
    autoLock30min = "30 dakika",
    autoLock1hr = "1 saat",
    settingsDecoySetup = "Tuzak Parolası Kur",
    settingsDecoySubtitle = "Gerçek verileri gizlemek için tuzak parolası ekle",
    autoLockTimeout = "Otomatik Kilit Süresi",
    securityLevel = "Güvenlik Seviyesi",
    exportImport = "Dışa / İçe Aktar",
    exportTitle = "Dışa Aktar",
    importTitle = "İçe Aktar",
    exportPassword = "Dışa Aktarma Parolası",
    exportFile = "Dışa Aktarma Dosyası",
    importFile = "İçe Aktarma Dosyası",
    exportSuccess = "Başarıyla dışa aktarıldı",
    importSuccess = "Başarıyla içe aktarıldı",
    about = "Hakkında",
    aboutVersion = "Sürüm",
    aboutDescription = "Askeri düzeyde şifrelemeye sahip güvenli bir not uygulaması.",
    aboutLicense = "MIT Lisansı",
    aboutTechStack = "Teknoloji Yığını:\n• Kotlin + Jetpack Compose\n• AES-256-GCM şifreleme\n• Argon2id anahtar türetme (64MB)\n• Room veritabanı (SQLCipher)\n• İnternet izni yok\n• Google Play Services yok",
    aboutThreatModelTitle = "Tehdit Modeli",
    aboutThreatModel = "Korunduğu tehditler:\n• Fiziksel cihaz ele geçirme (şifreli)\n• Kötü amaçlı uygulamalar (IPC yok, FLAG_SECURE)\n• Klavye kaydediciler (özel klavye)\n• Ekran görüntüsü (FLAG_SECURE)\n• Android yedek çıkarma (devre dışı)\n• Bulut senkronizasyon sızıntıları (internet yok)\n• Google/OS anahtar çıkarma (Keystore yok)\n\nSınırlamalar:\n• Ele geçirilmiş OS çekirdeğine karşı korumaz\n• Donanım klavye kaydedicilere karşı korumaz\n• Not açıkken RAM'de düz metin bulunur",
    aboutCommunityTitle = "Topluluğuma katıl",
    sidebarSecureVault = "Güvenli Kasa",
    sidebarDecoyVault = "Tuzak Kasa",
    sidebarAllNotes = "Tüm Notlar",
    sidebarFavorites = "Favoriler",
    sidebarEncryptDecrypt = "Şifrele/Çöz",
    sidebarTrash = "Çöp Kutusu",
    sidebarSettings = "Ayarlar",
    sidebarExportImport = "Dışa/İçe Aktar",
    sidebarAbout = "Hakkında",
    sidebarLockVault = "Kasayı Kilitle",
    exitTitle = "Taybeti'den çık?",
    exitMessage = "Çıkmak istediğine emin misin?",
    exitConfirm = "Çık",
    exitCancel = "İptal",
    copied = "Kopyalandı",
    decoded = "Çözüldü",
    platform = "Platform",
    noDecoyNotes = "Tuzak not yok",

    darkThemeSubtitle = "Karanlık ve aydınlık görünüm arasında geçiş yap",
    rootDetectionTitle = "Root Tespiti Uyarısı",
    rootDetectionSubtitle = "Cihaz root'lanmışsa uyar (daha az güvenli)",
    language = "Dil",
    selectLanguage = "Dil seç",
    sidebarInstructions = "Talimatlar",

    instructionsPromptTitle = "Güvenlik Talimatlarını Oku",
    instructionsPromptMessage = "Uygulamayı kullanmadan önce güvenlik talimatlarını okumanızı şiddetle tavsiye ederiz. Verilerinizi casus yazılımlardan, tuş kaydedicilerden ve gözetimden nasıl koruyacağınızı açıklar.",
    instructionsPromptView = "Talimatları Görüntüle",
    instructionsPromptSkip = "Atla",

    instructionsTitle = "Güvenlik Talimatları",
    instructionsIntro = "Dikkatlice okuyun. Güvenliğiniz bu adımları takip etmenize bağlıdır.",
    instructionsPasswordTitle = "1. Ana parolanızı şahsen seçin",
    instructionsPasswordDetails = "Ana parolanızı oluştururken kimsenin izlemediğinden emin olun. Yakında kameralar varsa yazarken ekrana bakmayın. Büyük harf, küçük harf, rakam ve sembol kombinasyonu kullanın. En az 8 karakter — daha uzun olması daha iyidir.",
    instructionsPaperTitle = "2. Kağıda yazın",
    instructionsPaperDetails = "Parolanızı asla dijital olarak saklamayın (ekran görüntüsü yok, not uygulaması yok, bulut yok). Fiziksel kağıda yazın ve güvenli bir yerde saklayın. Birisi kağıdınızı bulsa bile, yine de telefonunuza ihtiyacı var. Birisi telefonunuzu alsa bile, yine de kağıdınıza ihtiyacı var.",
    instructionsNoDigitalTitle = "3. Parolaları asla dijital olarak saklamayın",
    instructionsNoDigitalDetails = "Parolaları hiçbir dijital biçimde saklamayın — metin dosyası yok, parola yöneticisi yok, e-posta taslağı yok, bulut notu yok. Dijital kopyalar kopyalanabilir, hacklenebilir veya el konulabilir. Sadece kağıt.",
    instructionsNoReadAloudTitle = "4. Parolanızı asla yüksek sesle okumayın",
    instructionsNoReadAloudDetails = "Modern casus yazılımlar telefonunuzun mikrofonunu görünür işaretler olmadan etkinleştirebilir. Parolanızı asla söylemeyin. Tuş seslerini birinin duyabileceği bir yerde asla yazmayın. Cihazınızın her zaman dinlediğini varsayın.",
    instructionsHowToEncryptTitle = "Bir mesaj nasıl şifrelenir",
    instructionsHowToEncryptDetails = "Şifrele sekmesini açın → mesajınızı yazın → güçlü bir parola girin (veya Anahtar Oluştur'a dokunun) → Şifrele'ye dokunun. Çıktıyı güvenli bir şekilde kopyalayın. İsteğe bağlı olarak şifreli metni URL olarak gizleyebilirsiniz.",
    instructionsHowToDecryptTitle = "Bir mesaj nasıl deşifre edilir",
    instructionsHowToDecryptDetails = "Gizlenmiş bir URL aldıysanız: Gizle sekmesine yapıştırın, platformu seçin ve Çöz'e dokunun. Ardından Deşifre sekmesine geçin, çıkarılan metni yapıştırın, anahtarı girin ve Deşifre'ye dokunun. Ham şifreli metin aldıysanız, doğrudan Deşifre sekmesine yapıştırın.",
    instructionsMultiUserTitle = "Çok Kullanıcılı Şifreleme",
    instructionsMultiUserDetails = "İki veya daha fazla kişi şifreli mesajlaşmak istediğinde: Fiziksel olarak buluşup parolayı birlikte oluşturun. Herkes kağıda yazıp çok güvenli bir yerde saklasın. Parola ASLA dijital olarak gönderilmemelidir — SMS, mesajlaşma uygulaması, e-posta veya bulut üzerinden asla. Sadece şifrelenmiş sonuç cihazdan çıkabilir.",
    instructionsMultiUserFriends = "Arkadaşların ve Ailenle Şifrelemeyi Paylaş",
    instructionsMultiUserFriendsDetails = "Fiziksel olarak buluşup ortak parola belirleyin. Herkes kağıda yazsın. Şifreleme aracını kullan, sadece şifreli çıktıyı paylaş.",
    instructionsCheckWebsite = "🔁 Güncellemeler için: Yeni sürümler için düzenli olarak web sitemizi ziyaret edin:\nhttps://cyberboy161.github.io/Taybeti/",
    instructionsMistakesTitle = "Kaçınılması gereken yaygın hatalar",
    instructionsMistake1 = "❌ Birden fazla not veya hesap için aynı parolayı kullanmak",
    instructionsMistake2 = "❌ Anahtarları bulut notlarında, e-postada veya mesajlaşma uygulamalarında saklamak",
    instructionsMistake3 = "❌ Kameraların veya omuz dikizcilerinin olduğu halka açık yerlerde parola yazmak",
    instructionsMistake4 = "❌ Kısa, sözlük tabanlı veya tahmin edilebilir parolalar kullanmak",
    instructionsWarningTitle = "⚠️ Önemli Uyarılar",
    instructionsWarning1 = "Ana parolanızı ASLA kimseyle paylaşmayın — destek veya kolluk kuvvetleriyle bile",
    instructionsWarning2 = "Parolanızı unutursanız, verileriniz KURTARILAMAZ — arka kapı yoktur",
    instructionsWarning3 = "5 yanlış denemeden sonra 30 saniyelik bir kilit devreye girer — bu, brute-force saldırılarını önler",
)
